// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "adder": Application Media Types
//
// Command:
// $ goagen
// --design=ping-in/design
<<<<<<< HEAD
// --out=$(GOPATH)/src/github.com/athagi/src/ping-in
=======
// --out=$(GOPATH)\src\github.com\athagi\src\ping-in
>>>>>>> test
// --version=v1.3.1

package client
