consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
host: localhost:8080
info:
  description: A teaser for goa
  title: The adder API
  version: ""
paths:
  /add/{left}/{right}:
    get:
      description: add returns the sum of the left and right parameters in the response
        body
      operationId: operands#add
      parameters:
      - description: Left operand
        in: path
        name: left
        required: true
        type: integer
      - description: Right operand
        in: path
        name: right
        required: true
        type: integer
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: add operands
      tags:
      - operands
  /uri/host/{host_name}:
    get:
      description: add uri to check endpoint
      operationId: uri#host
      parameters:
      - description: hostname
        in: path
        name: host_name
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: host uri
      tags:
      - uri
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
schemes:
- http
swagger: "2.0"
