// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "adder": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=ping-in/design
<<<<<<< HEAD
// --out=$(GOPATH)/src/github.com/athagi/src/ping-in
=======
// --out=$(GOPATH)\src\github.com\athagi\src\ping-in
>>>>>>> 43148370a26d650f15d31edbb5a25e362f72f7d6
// --version=v1.3.1

package app
