// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "adder": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=ping-in/design
// --out=$(GOPATH)\src\github.com\athagi\src\ping-in
// --version=v1.3.1

package app
